## *********************************************************
##
## File autogenerated for the dynamic_gap package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'name': 'Default', 'type': '', 'state': True, 'cstate': 'true', 'id': 0, 'parent': 0, 'parameters': [], 'groups': [{'name': 'Control', 'type': 'tab', 'state': True, 'cstate': 'true', 'id': 1, 'parent': 0, 'parameters': [{'name': 'linear_vel_x', 'type': 'double', 'default': 0.0, 'level': 0, 'description': 'Linear velocity x', 'min': -1.0, 'max': 1.0, 'srcline': 10, 'srcfile': '/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}, {'name': 'linear_vel_y', 'type': 'double', 'default': 0.0, 'level': 0, 'description': 'Linear velocity y', 'min': -1.0, 'max': 1.0, 'srcline': 11, 'srcfile': '/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}, {'name': 'angular_vel_z', 'type': 'double', 'default': 0.0, 'level': 0, 'description': 'Angular velocity z', 'min': -1.0, 'max': 1.0, 'srcline': 12, 'srcfile': '/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}], 'groups': [], 'srcline': 125, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'class': 'DEFAULT::CONTROL', 'parentclass': 'DEFAULT', 'parentname': 'Default', 'field': 'DEFAULT::control', 'upper': 'CONTROL', 'lower': 'control'}], 'srcline': 247, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'class': 'DEFAULT', 'parentclass': '', 'parentname': 'Default', 'field': 'default', 'upper': 'DEFAULT', 'lower': 'groups'}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

