## *********************************************************
##
## File autogenerated for the dynamic_gap package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'name': 'Default', 'type': '', 'state': True, 'cstate': 'true', 'id': 0, 'parent': 0, 'parameters': [], 'groups': [{'name': 'Model_Estimation', 'type': 'tab', 'state': True, 'cstate': 'true', 'id': 1, 'parent': 0, 'parameters': [{'name': 'Q', 'type': 'double', 'default': 0.01, 'level': 0, 'description': 'Model noise parameter', 'min': 0.0, 'max': 100.0, 'srcline': 10, 'srcfile': '/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}, {'name': 'R', 'type': 'double', 'default': 0.01, 'level': 0, 'description': 'Sensor noise parameter', 'min': 0.0, 'max': 100.0, 'srcline': 11, 'srcfile': '/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}], 'groups': [], 'srcline': 125, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'class': 'DEFAULT::MODEL_ESTIMATION', 'parentclass': 'DEFAULT', 'parentname': 'Default', 'field': 'DEFAULT::model_estimation', 'upper': 'MODEL_ESTIMATION', 'lower': 'model_estimation'}], 'srcline': 247, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'class': 'DEFAULT', 'parentclass': '', 'parentname': 'Default', 'field': 'default', 'upper': 'DEFAULT', 'lower': 'groups'}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

