set(_CATKIN_CURRENT_PACKAGE "global_planner_setup")
set(global_planner_setup_VERSION "0.0.0")
set(global_planner_setup_MAINTAINER "p14 <p14@todo.todo>")
set(global_planner_setup_PACKAGE_FORMAT "2")
set(global_planner_setup_BUILD_DEPENDS "move_base" "nav_msgs" "rospy" "std_msgs")
set(global_planner_setup_BUILD_EXPORT_DEPENDS "move_base" "nav_msgs" "rospy" "std_msgs")
set(global_planner_setup_BUILDTOOL_DEPENDS "catkin")
set(global_planner_setup_BUILDTOOL_EXPORT_DEPENDS )
set(global_planner_setup_EXEC_DEPENDS "move_base" "nav_msgs" "rospy" "std_msgs")
set(global_planner_setup_RUN_DEPENDS "move_base" "nav_msgs" "rospy" "std_msgs")
set(global_planner_setup_TEST_DEPENDS )
set(global_planner_setup_DOC_DEPENDS )
set(global_planner_setup_URL_WEBSITE "")
set(global_planner_setup_URL_BUGTRACKER "")
set(global_planner_setup_URL_REPOSITORY "")
set(global_planner_setup_DEPRECATED "")