#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_simulator:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_gazebo_plugins:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_description:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_visualizer:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_simulator:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_sensors:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_utils:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_srvs:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_ros:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_gazebo_plugin:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/dynamic_gap:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_msgs:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/multi_robot_scenario:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/global_planner_setup:/opt/ros/noetic'
export LD_LIBRARY_PATH='/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_gazebo_plugins/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_description/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_visualizer/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_simulator/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_sensors/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_utils/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_srvs/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_gazebo_plugin/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/dynamic_gap/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_msgs/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/multi_robot_scenario/lib:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/global_planner_setup/lib:/opt/ros/noetic/lib'
export PKG_CONFIG_PATH='/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_gazebo_plugins/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_description/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_visualizer/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_simulator/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_sensors/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_utils/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_srvs/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_gazebo_plugin/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/dynamic_gap/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_msgs/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/multi_robot_scenario/lib/pkgconfig:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/global_planner_setup/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig'
export PWD='/home/p14/DRL-robot-navigation/catkin_ws/build_isolated/global_planner_setup'
export ROSLISP_PACKAGE_DIRECTORIES='/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_simulator/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_gazebo_plugins/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/velodyne_description/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_visualizer/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_simulator/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_sensors/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_utils/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_srvs/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_ros/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_gazebo_plugin/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/dynamic_gap/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim_msgs/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/pedsim/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/multi_robot_scenario/share/common-lisp:/home/p14/DRL-robot-navigation/catkin_ws/devel_isolated/global_planner_setup/share/common-lisp'
export ROS_PACKAGE_PATH='/home/p14/DRL-robot-navigation/catkin_ws/src/velodyne_simulator/velodyne_simulator:/home/p14/DRL-robot-navigation/catkin_ws/src/velodyne_simulator/velodyne_gazebo_plugins:/home/p14/DRL-robot-navigation/catkin_ws/src/velodyne_simulator/velodyne_description:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_visualizer:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_simulator:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_sensors:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_utils:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_srvs:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_ros:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_gazebo_plugin:/home/p14/DRL-robot-navigation/catkin_ws/src/dynamic_gap:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/pedsim_msgs:/home/p14/DRL-robot-navigation/catkin_ws/src/pedsim_ros/3rdparty/libpedsim:/home/p14/DRL-robot-navigation/catkin_ws/src/multi_robot_scenario:/home/p14/DRL-robot-navigation/catkin_ws/src/global_planner_setup:/opt/ros/noetic/share'