//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dynamic_gap package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dynamic_gap__CONTROLPARAMETERSCONFIG_H__
#define __dynamic_gap__CONTROLPARAMETERSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic_gap
{
  class ControlParametersConfigStatics;

  class ControlParametersConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ControlParametersConfig &config, const ControlParametersConfig &max, const ControlParametersConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ControlParametersConfig &config1, const ControlParametersConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ControlParametersConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ControlParametersConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ControlParametersConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ControlParametersConfig &config) const = 0;
      virtual void getValue(const ControlParametersConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ControlParametersConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ControlParametersConfig::* field;

      virtual void clamp(ControlParametersConfig &config, const ControlParametersConfig &max, const ControlParametersConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ControlParametersConfig &config1, const ControlParametersConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ControlParametersConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ControlParametersConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ControlParametersConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ControlParametersConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ControlParametersConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ControlParametersConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ControlParametersConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ControlParametersConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ControlParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class CONTROL
{
  public:
    CONTROL()
    {
      state = true;
      name = "Control";
    }

    void setParams(ControlParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("linear_vel_x"==(*_i)->name){linear_vel_x = boost::any_cast<double>(val);}
        if("linear_vel_y"==(*_i)->name){linear_vel_y = boost::any_cast<double>(val);}
        if("angular_vel_z"==(*_i)->name){angular_vel_z = boost::any_cast<double>(val);}
      }
    }

    double linear_vel_x;
double linear_vel_y;
double angular_vel_z;

    bool state;
    std::string name;

    
}control;

}groups;



//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      double linear_vel_x;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      double linear_vel_y;
//#line 12 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      double angular_vel_z;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ControlParametersConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ControlParametersConfig &__max__ = __getMax__();
      const ControlParametersConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ControlParametersConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ControlParametersConfig &__getDefault__();
    static const ControlParametersConfig &__getMax__();
    static const ControlParametersConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ControlParametersConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ControlParametersConfig::ParamDescription<std::string>::clamp(ControlParametersConfig &config, const ControlParametersConfig &max, const ControlParametersConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ControlParametersConfigStatics
  {
    friend class ControlParametersConfig;

    ControlParametersConfigStatics()
    {
ControlParametersConfig::GroupDescription<ControlParametersConfig::DEFAULT, ControlParametersConfig> Default("Default", "", 0, 0, true, &ControlParametersConfig::groups);
ControlParametersConfig::GroupDescription<ControlParametersConfig::DEFAULT::CONTROL, ControlParametersConfig::DEFAULT> Control("Control", "tab", 0, 1, true, &ControlParametersConfig::DEFAULT::control);
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __min__.linear_vel_x = -1.0;
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __max__.linear_vel_x = 1.0;
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __default__.linear_vel_x = 0.0;
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      Control.abstract_parameters.push_back(ControlParametersConfig::AbstractParamDescriptionConstPtr(new ControlParametersConfig::ParamDescription<double>("linear_vel_x", "double", 0, "Linear velocity x", "", &ControlParametersConfig::linear_vel_x)));
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __param_descriptions__.push_back(ControlParametersConfig::AbstractParamDescriptionConstPtr(new ControlParametersConfig::ParamDescription<double>("linear_vel_x", "double", 0, "Linear velocity x", "", &ControlParametersConfig::linear_vel_x)));
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __min__.linear_vel_y = -1.0;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __max__.linear_vel_y = 1.0;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __default__.linear_vel_y = 0.0;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      Control.abstract_parameters.push_back(ControlParametersConfig::AbstractParamDescriptionConstPtr(new ControlParametersConfig::ParamDescription<double>("linear_vel_y", "double", 0, "Linear velocity y", "", &ControlParametersConfig::linear_vel_y)));
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __param_descriptions__.push_back(ControlParametersConfig::AbstractParamDescriptionConstPtr(new ControlParametersConfig::ParamDescription<double>("linear_vel_y", "double", 0, "Linear velocity y", "", &ControlParametersConfig::linear_vel_y)));
//#line 12 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __min__.angular_vel_z = -1.0;
//#line 12 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __max__.angular_vel_z = 1.0;
//#line 12 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __default__.angular_vel_z = 0.0;
//#line 12 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      Control.abstract_parameters.push_back(ControlParametersConfig::AbstractParamDescriptionConstPtr(new ControlParametersConfig::ParamDescription<double>("angular_vel_z", "double", 0, "Angular velocity z", "", &ControlParametersConfig::angular_vel_z)));
//#line 12 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/ControlParameters.cfg"
      __param_descriptions__.push_back(ControlParametersConfig::AbstractParamDescriptionConstPtr(new ControlParametersConfig::ParamDescription<double>("angular_vel_z", "double", 0, "Angular velocity z", "", &ControlParametersConfig::angular_vel_z)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Control.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ControlParametersConfig::AbstractGroupDescriptionConstPtr(new ControlParametersConfig::GroupDescription<ControlParametersConfig::DEFAULT::CONTROL, ControlParametersConfig::DEFAULT>(Control)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ControlParametersConfig::AbstractGroupDescriptionConstPtr(new ControlParametersConfig::GroupDescription<ControlParametersConfig::DEFAULT::CONTROL, ControlParametersConfig::DEFAULT>(Control)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ControlParametersConfig::AbstractGroupDescriptionConstPtr(new ControlParametersConfig::GroupDescription<ControlParametersConfig::DEFAULT, ControlParametersConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ControlParametersConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ControlParametersConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ControlParametersConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ControlParametersConfig __max__;
    ControlParametersConfig __min__;
    ControlParametersConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ControlParametersConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ControlParametersConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ControlParametersConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ControlParametersConfig &ControlParametersConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ControlParametersConfig &ControlParametersConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ControlParametersConfig &ControlParametersConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ControlParametersConfig::AbstractParamDescriptionConstPtr> &ControlParametersConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ControlParametersConfig::AbstractGroupDescriptionConstPtr> &ControlParametersConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ControlParametersConfigStatics *ControlParametersConfig::__get_statics__()
  {
    const static ControlParametersConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ControlParametersConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CONTROLPARAMETERSRECONFIGURATOR_H__
