//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dynamic_gap package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dynamic_gap__ESTIMATIONPARAMETERSCONFIG_H__
#define __dynamic_gap__ESTIMATIONPARAMETERSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic_gap
{
  class EstimationParametersConfigStatics;

  class EstimationParametersConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(EstimationParametersConfig &config, const EstimationParametersConfig &max, const EstimationParametersConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const EstimationParametersConfig &config1, const EstimationParametersConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, EstimationParametersConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const EstimationParametersConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, EstimationParametersConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const EstimationParametersConfig &config) const = 0;
      virtual void getValue(const EstimationParametersConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T EstimationParametersConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T EstimationParametersConfig::* field;

      virtual void clamp(EstimationParametersConfig &config, const EstimationParametersConfig &max, const EstimationParametersConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const EstimationParametersConfig &config1, const EstimationParametersConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, EstimationParametersConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const EstimationParametersConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, EstimationParametersConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const EstimationParametersConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const EstimationParametersConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, EstimationParametersConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, EstimationParametersConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<EstimationParametersConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(EstimationParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class MODEL_ESTIMATION
{
  public:
    MODEL_ESTIMATION()
    {
      state = true;
      name = "Model_Estimation";
    }

    void setParams(EstimationParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Q"==(*_i)->name){Q = boost::any_cast<double>(val);}
        if("R"==(*_i)->name){R = boost::any_cast<double>(val);}
      }
    }

    double Q;
double R;

    bool state;
    std::string name;

    
}model_estimation;

}groups;



//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      double Q;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      double R;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("EstimationParametersConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const EstimationParametersConfig &__max__ = __getMax__();
      const EstimationParametersConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const EstimationParametersConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const EstimationParametersConfig &__getDefault__();
    static const EstimationParametersConfig &__getMax__();
    static const EstimationParametersConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const EstimationParametersConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void EstimationParametersConfig::ParamDescription<std::string>::clamp(EstimationParametersConfig &config, const EstimationParametersConfig &max, const EstimationParametersConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class EstimationParametersConfigStatics
  {
    friend class EstimationParametersConfig;

    EstimationParametersConfigStatics()
    {
EstimationParametersConfig::GroupDescription<EstimationParametersConfig::DEFAULT, EstimationParametersConfig> Default("Default", "", 0, 0, true, &EstimationParametersConfig::groups);
EstimationParametersConfig::GroupDescription<EstimationParametersConfig::DEFAULT::MODEL_ESTIMATION, EstimationParametersConfig::DEFAULT> Model_Estimation("Model_Estimation", "tab", 0, 1, true, &EstimationParametersConfig::DEFAULT::model_estimation);
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __min__.Q = 0.0;
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __max__.Q = 100.0;
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __default__.Q = 0.01;
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      Model_Estimation.abstract_parameters.push_back(EstimationParametersConfig::AbstractParamDescriptionConstPtr(new EstimationParametersConfig::ParamDescription<double>("Q", "double", 0, "Model noise parameter", "", &EstimationParametersConfig::Q)));
//#line 10 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __param_descriptions__.push_back(EstimationParametersConfig::AbstractParamDescriptionConstPtr(new EstimationParametersConfig::ParamDescription<double>("Q", "double", 0, "Model noise parameter", "", &EstimationParametersConfig::Q)));
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __min__.R = 0.0;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __max__.R = 100.0;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __default__.R = 0.01;
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      Model_Estimation.abstract_parameters.push_back(EstimationParametersConfig::AbstractParamDescriptionConstPtr(new EstimationParametersConfig::ParamDescription<double>("R", "double", 0, "Sensor noise parameter", "", &EstimationParametersConfig::R)));
//#line 11 "/home/power20/DRL-robot-navigation/catkin_ws/src/dynamic_gap/cfg/EstimationParameters.cfg"
      __param_descriptions__.push_back(EstimationParametersConfig::AbstractParamDescriptionConstPtr(new EstimationParametersConfig::ParamDescription<double>("R", "double", 0, "Sensor noise parameter", "", &EstimationParametersConfig::R)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Model_Estimation.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(EstimationParametersConfig::AbstractGroupDescriptionConstPtr(new EstimationParametersConfig::GroupDescription<EstimationParametersConfig::DEFAULT::MODEL_ESTIMATION, EstimationParametersConfig::DEFAULT>(Model_Estimation)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(EstimationParametersConfig::AbstractGroupDescriptionConstPtr(new EstimationParametersConfig::GroupDescription<EstimationParametersConfig::DEFAULT::MODEL_ESTIMATION, EstimationParametersConfig::DEFAULT>(Model_Estimation)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(EstimationParametersConfig::AbstractGroupDescriptionConstPtr(new EstimationParametersConfig::GroupDescription<EstimationParametersConfig::DEFAULT, EstimationParametersConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<EstimationParametersConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<EstimationParametersConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<EstimationParametersConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    EstimationParametersConfig __max__;
    EstimationParametersConfig __min__;
    EstimationParametersConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const EstimationParametersConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static EstimationParametersConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &EstimationParametersConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const EstimationParametersConfig &EstimationParametersConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const EstimationParametersConfig &EstimationParametersConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const EstimationParametersConfig &EstimationParametersConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<EstimationParametersConfig::AbstractParamDescriptionConstPtr> &EstimationParametersConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<EstimationParametersConfig::AbstractGroupDescriptionConstPtr> &EstimationParametersConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const EstimationParametersConfigStatics *EstimationParametersConfig::__get_statics__()
  {
    const static EstimationParametersConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = EstimationParametersConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ESTIMATIONPARAMETERSRECONFIGURATOR_H__
