set(_CATKIN_CURRENT_PACKAGE "ground_truth_localization")
set(ground_truth_localization_VERSION "0.0.0")
set(ground_truth_localization_MAINTAINER "az <az@todo.todo>")
set(ground_truth_localization_PACKAGE_FORMAT "2")
set(ground_truth_localization_BUILD_DEPENDS "gazebo_msgs" "geometry_msgs" "rospy" "tf")
set(ground_truth_localization_BUILD_EXPORT_DEPENDS "gazebo_msgs" "geometry_msgs" "rospy" "tf")
set(ground_truth_localization_BUILDTOOL_DEPENDS "catkin")
set(ground_truth_localization_BUILDTOOL_EXPORT_DEPENDS )
set(ground_truth_localization_EXEC_DEPENDS "gazebo_msgs" "geometry_msgs" "rospy" "tf")
set(ground_truth_localization_RUN_DEPENDS "gazebo_msgs" "geometry_msgs" "rospy" "tf")
set(ground_truth_localization_TEST_DEPENDS )
set(ground_truth_localization_DOC_DEPENDS )
set(ground_truth_localization_URL_WEBSITE "")
set(ground_truth_localization_URL_BUGTRACKER "")
set(ground_truth_localization_URL_REPOSITORY "")
set(ground_truth_localization_DEPRECATED "")